---
artifact_definitions:
  - name: "Openconfig Interface for Arista devices"
    artifact_name: "openconfig-interfaces"
    parameters:
      device: "name__value"
    content_type: "application/json"
    targets: "arista_devices"
    transformation: "OCInterfaces"
  - name: "Openconfig BGP for Artista devices"
    artifact_name: "openconfig-bgp"
    parameters:
      device: "name__value"
    content_type: "application/json"
    targets: "arista_devices"
    transformation: "OCBGPNeighbors"
  - name: "Config for Arista devices"
    artifact_name: "config-arista"
    parameters:
      device: "name__value"
    targets: "arista_devices"
    transformation: "arista_config"

python_transforms:
  - name: OCInterfaces
    class_name: OCInterfaces
    file_path: "transforms/openconfig.py"
  - name: OCBGPNeighbors
    class_name: OCBGPNeighbors
    file_path: "transforms/openconfig.py"

jinja2_transforms:
  - name: "arista_config"
    description: "Template to generate startup configuration for arista routers"
    query: "arista_router_config"
    template_path: "templates/arista_router_config.j2"
