---
check_definitions:
  - name: "BGP transit session check"
    file_path: "./checks/check_bgp_transit_session.py"
    # parameters:
    # targets:
    class_name: "SonyBGPSessionCheck"

artifact_definitions:
  - name: "Config for Arista devices"
    artifact_name: "config-arista"
    parameters:
      device: "name__value"
    content_type: "text/plain"
    targets: "arista_devices"
    transformation: "arista_config"


jinja2_transforms:
  - name: "arista_config"
    description: "Template to generate startup configuration for arista routers"
    query: "arista_router_config"
    template_path: "templates/arista_router_config.j2"
