query($device: String!) {
    device(name__value: $device) {
        id
        name {
            value
        }
        asn {
            asn {
                value
            }
        }
        interfaces {
            id
            name {
                value
            }
            description {
                value
            }
            enabled {
                value
            }
            role {
                name {
                    value
                }
            }
            ip_addresses {
                address {
                    value
                }
            }
        }
    }
    bgp_peer_group {
        name {
            value
        }
        local_as {
            asn {
                value
            }
        }
        remote_as {
            asn {
                value
            }
        }
    }
}