query($branch: String!, $device: String!) {
    device(branch: $branch, name__value: $device) {
        id
        name {
            value
        }
        asn {
            asn {
                value
            }
        }
        interfaces {
            id
            name {
                value
            }
            description {
                value
            }
            enabled {
                value
            }
            role {
                slug {
                    value
                }
            }
            ip_addresses {
                address {
                    value
                }
            }
        }
        management_interface: interfaces(role__slug: "management") {
            name {
                value
            }
            ip_addresses {
                address {
                    value
                }
            }
        }
    }
    bgp_peer_group {
        name {
            value
        }
        local_as {
            asn {
                value
            }
        }
        remote_as {
            asn {
                value
            }
        }
    }
}