query {
    device {
        name {
            value
        }
        interfaces(role__slug: "management") {
            id
            ip_addresses {
                address {
                    value
                }
            }
        }
    }
}