query($device: String!) {
  device(name__value: $device) {
    edges {
      node {
        id
        name {
          value
        }
        asn {
          node {
            asn {
              value
            }
          }
        }
        interfaces {
          edges {
            node {
              id
              name {
                value
              }
              description {
                value
              }
              enabled {
                value
              }
              role {
                node {
                  name {
                    value
                  }
                }
              }
              ... on InterfaceL3 {
                ip_addresses {
                  edges {
                    node {
                      address {
                        value
                      }
                    }
                  }
                }
              }
            }
          }
        }

      }
    }
  }
  bgp_peer_group {
    edges {
      node {
        name {
          value
        }
        local_as {
          node {
            asn {
              value
            }
          }
        }
        remote_as {
          node {
            asn {
              value
            }
          }
        }
      }
    }
  }
}