query ($branch: String!, $rebase: Boolean!) {
    circuit(branch: $branch, role__name__value: "backbone", rebase: $rebase) {
        id
        circuit_id {
            value
        }
        vendor_id {
            value
        }
        status {
            name {
                value
            }
        }
        endpoints {
            site {
                id
                name {
                    value
                }
            }
            connected_interface {
                enabled {
                    value
                }
            }
        }
    }
}
