query {
    circuit(role__name__value: "backbone") {
        id
        circuit_id {
            value
        }
        vendor_id {
            value
        }
        status {
            name {
                value
            }
        }
        endpoints {
            site {
                id
                name {
                    value
                }
            }
            connected_interface {
                enabled {
                    value
                }
            }
        }
    }
}
